name: Web

on:
  push:
    branches:
      - gh-pages
  pull_request:
    branches:
      - gh-pages
      
  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: configure
        uses: actions/configure-pages@v3
      - name: upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v2
